name: Hello Github Actions
run-name: ${{ github.actor }} is saying hello 👋
on:
  push:
    branches:
      - main


jobs:
  initial-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Save secrets to file
        run: |
          mkdir -p ./secrets
          echo "${{ secrets.TOKEN1 }}" > ./secrets/token1

      - name: Cache secrets
        uses: actions/cache@v3
        with:
          path: ./secrets
          key: ${{ runner.os }}-secrets-${{ github.run_id }}

  subsequent-job:
    needs: initial-job
    runs-on: ubuntu-latest
    # No environment: production needed here
    steps:
      - name: Restore cached secrets
        uses: actions/cache@v3
        with:
          path: ./secrets
          key: ${{ runner.os }}-secrets-${{ github.run_id }}

      - name: Use secrets
        run: |
          TOKEN1=$(cat ./secrets/token1)
          echo "Using secret (masked for security): $TOKEN1"