name: Hello Github Actions
run-name: ${{ github.actor }} is saying hello 👋
on:
  push:
    branches:
      - main

jobs:
  j_set_name:
    environment: development
    name: Set name job
    outputs:
      name: ${{ steps.s_set_name.outputs.name }}
      token1: ${{ steps.s_set_secret.outputs.token1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Set name step
        id: s_set_name
        run: |
          echo "name=Max" >> $GITHUB_OUTPUT
          echo "name=Mona" >> $GITHUB_OUTPUT
      - name: Set secret step
        id: s_set_secret
        run: |
          TOKEN1=${{ secrets.TOKEN1 }}
          echo "::add-mask::${{ secrets.TOKEN1 }}"
          echo "token1=${{ secrets.TOKEN1 }}" >> $GITHUB_OUTPUT
  j_print_name:
    name: Print name job
    needs: [ j_set_name ]
    runs-on: ubuntu-latest
    steps:
      - name: Print name step
        run: |
          echo "Hi ${{ needs.j_set_name.outputs.name }}"
      - name: Consume secret
        run: |
          # The secret is available as:
          echo "Using secret: ${{ needs.j_set_name.outputs.token1 }}"
          # Use it in your commands
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
  j_dev_context:
    name: Exploring dev configuration
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Print development configuration variable
        run: |
          echo "FOO=${{ vars.FOO }}"
  j_test_context:
    name: Exploring test configuration
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Print development configuration variable
        run: |
          echo "FOO=${{ vars.FOO }}"
